import { Activity, FileText, HeartPulse, ShieldCheck, Stethoscope, Upload } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export default function StyleGuidePage() {
  return <main className="min-h-screen gradient-healthcare-soft px-6 py-14"><div className="mx-auto max-w-5xl space-y-10"><header className="space-y-3"><div className="flex items-center gap-2 text-sm font-bold text-primary"><HeartPulse className="size-5" /> ELEOS MEDICAL</div><h1 className="text-4xl font-extrabold tracking-tight text-gradient-healthcare">Healthcare design system</h1><p className="max-w-2xl text-healthcare-soft-ink">A calm, approachable system for clear and trustworthy care experiences.</p></header><section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl gradient-healthcare p-5 text-white"><p className="text-sm font-medium opacity-80">Primary</p><p className="mt-1 font-bold">Core visual tone</p></div><div className="rounded-2xl bg-healthcare-pink p-5 text-white"><p className="text-sm font-medium opacity-80">Accent</p><p className="mt-1 font-bold">Supportive highlight</p></div><div className="rounded-2xl border border-healthcare-lilac bg-white p-5 text-healthcare-ink"><p className="text-sm font-medium text-healthcare-soft-ink">Surface</p><p className="mt-1 font-bold">Soft lavender + white</p></div></section><section className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><div><CardTitle>Actions</CardTitle><CardDescription>Buttons support clinical workflows and supportive prompts.</CardDescription></div><Stethoscope className="size-7 text-primary" /></CardHeader><CardContent className="flex flex-wrap gap-3"><Button><Activity className="size-4" />View activity</Button><Button variant="secondary"><FileText className="size-4" />Records</Button><Button variant="outline"><Upload className="size-4" />Upload file</Button><Button variant="ghost">Learn more</Button></CardContent></Card><Card><CardHeader><div><CardTitle>Form controls</CardTitle><CardDescription>Clear fields with soft focus treatment.</CardDescription></div><ShieldCheck className="size-7 text-primary" /></CardHeader><CardContent><Input label="Patient email" type="email" placeholder="patient@example.com" icon={<HeartPulse className="size-4" />} /></CardContent></Card></section><section className="grid gap-6 lg:grid-cols-[1.3fr_1fr]"><Card><CardHeader><div><CardTitle>Status badges</CardTitle><CardDescription>Use concise states to reinforce confidence and clarity.</CardDescription></div></CardHeader><CardContent className="flex flex-wrap gap-3"><Badge><Activity className="size-3.5" />In progress</Badge><Badge variant="pink"><HeartPulse className="size-3.5" />Priority care</Badge><Badge variant="success"><ShieldCheck className="size-3.5" />Verified</Badge><Badge variant="outline">New result</Badge></CardContent></Card><Card className="gradient-healthcare text-white"><CardTitle className="text-white">Care, made clearer.</CardTitle><CardDescription className="mt-2 text-white/80">A foundation that feels warm, modern, and human.</CardDescription></Card></section></div></main>;
}
