"use client";

import { motion } from "framer-motion";
import { Activity, ArrowRight, FileText, HeartPulse, ImageIcon, ShieldCheck, Sparkles, Stethoscope, Upload } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const steps: { icon: LucideIcon; title: string; description: string }[] = [
  { icon: Upload, title: "Upload", description: "Choose a report image or PDF when you are ready." },
  { icon: Sparkles, title: "AI analyzes", description: "Your report is translated into clearer everyday language." },
  { icon: FileText, title: "Get a simple explanation", description: "Read the findings and unfamiliar terms with more confidence." },
];

const features: { icon: LucideIcon; title: string; description: string }[] = [
  { icon: ImageIcon, title: "X-rays", description: "Make radiology language easier to follow." },
  { icon: Activity, title: "Lab reports", description: "Understand the context behind your results." },
  { icon: FileText, title: "Discharge summaries", description: "Clarify the key details from your care visit." },
  { icon: Stethoscope, title: "Diagnostic imaging", description: "Read imaging reports without the jargon." },
];

const reveal = { hidden: { opacity: 0, y: 22 }, visible: { opacity: 1, y: 0 } };

export default function Home() {
  return (
    <main className="overflow-hidden bg-background text-healthcare-ink">
      <section className="relative isolate">
        <div className="absolute inset-x-0 top-0 -z-10 h-[42rem] gradient-healthcare-soft" />
        <div className="absolute -left-24 top-24 -z-10 size-80 rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute -right-20 top-40 -z-10 size-72 rounded-full bg-healthcare-pink/10 blur-3xl" />
        <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6 lg:px-8" aria-label="Main navigation"><a className="flex items-center gap-2 font-extrabold tracking-tight text-healthcare-ink" href="#top"><span className="flex size-9 items-center justify-center rounded-xl gradient-healthcare text-white shadow-healthcare"><HeartPulse className="size-5" /></span>Eleos Medical</a><div className="hidden items-center gap-7 text-sm font-semibold text-healthcare-soft-ink sm:flex"><a className="transition hover:text-primary" href="#how-it-works">How it works</a><a className="transition hover:text-primary" href="#features">Features</a></div><Button asChild size="sm"><a href="#how-it-works">Get started <ArrowRight className="size-4" /></a></Button></nav>
        <div id="top" className="mx-auto grid max-w-6xl items-center gap-12 px-6 pb-20 pt-12 lg:grid-cols-[1.1fr_0.9fr] lg:px-8 lg:pb-28 lg:pt-20">
          <motion.div initial="hidden" animate="visible" transition={{ staggerChildren: 0.11 }} className="max-w-2xl space-y-7"><motion.div variants={reveal} transition={{ duration: 0.45 }} className="inline-flex items-center gap-2 rounded-full border border-primary/15 bg-white/80 px-3 py-1.5 text-sm font-semibold text-primary shadow-sm backdrop-blur"><ShieldCheck className="size-4" />Clearer health information, thoughtfully explained</motion.div><motion.h1 variants={reveal} transition={{ duration: 0.5 }} className="text-4xl font-extrabold leading-tight tracking-tight text-healthcare-ink sm:text-5xl lg:text-6xl">Understand your medical reports in <span className="text-gradient-healthcare">plain language.</span></motion.h1><motion.p variants={reveal} transition={{ duration: 0.5 }} className="max-w-xl text-lg leading-8 text-healthcare-soft-ink">Eleos Medical helps turn complex report wording into a simple, approachable explanation so you can have a more informed conversation with your doctor.</motion.p><motion.div variants={reveal} transition={{ duration: 0.5 }} className="flex flex-wrap gap-3"><Button asChild size="lg"><a href="#how-it-works">Get Started <ArrowRight className="size-4" /></a></Button><Button asChild variant="outline" size="lg"><a href="#how-it-works">See how it works</a></Button></motion.div></motion.div>
          <motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.7, delay: 0.18 }} className="relative mx-auto w-full max-w-md"><div className="rounded-[2rem] border border-white/70 bg-white/65 p-5 shadow-healthcare backdrop-blur-xl sm:p-7"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl gradient-healthcare text-white"><FileText className="size-5" /></span><div><p className="font-bold">Your report, simplified</p><p className="text-xs text-healthcare-soft-ink">Clear and easy to read</p></div></div><ShieldCheck className="size-5 text-primary" /></div><div className="mt-7 space-y-3"><div className="h-2.5 w-3/4 rounded-full bg-healthcare-lilac" /><div className="h-2.5 w-full rounded-full bg-healthcare-lavender" /><div className="h-2.5 w-5/6 rounded-full bg-healthcare-lavender" /></div><div className="mt-7 rounded-2xl bg-healthcare-lavender p-4"><p className="text-sm font-semibold text-primary">Medical terms, made easier</p><p className="mt-1 text-sm leading-6 text-healthcare-soft-ink">A guided explanation to help you prepare for the conversation that matters.</p></div></div><motion.div animate={{ y: [0, -10, 0] }} transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }} className="absolute -left-5 top-20 flex size-14 items-center justify-center rounded-2xl bg-white text-primary shadow-healthcare"><HeartPulse className="size-7" /></motion.div><motion.div animate={{ y: [0, 11, 0] }} transition={{ duration: 4.6, repeat: Infinity, ease: "easeInOut", delay: 0.35 }} className="absolute -right-5 bottom-10 flex size-14 items-center justify-center rounded-2xl bg-white text-healthcare-pink shadow-healthcare"><Stethoscope className="size-7" /></motion.div></motion.div>
        </div>
      </section>
      <section className="mx-auto max-w-6xl px-6 py-6 lg:px-8"><div className="rounded-2xl border border-primary/20 bg-white p-5 shadow-healthcare"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" /><p className="text-sm font-semibold leading-6 text-healthcare-ink">This tool provides educational simplification only and is not a substitute for professional medical advice, diagnosis, or treatment.</p></div></div></section>
      <motion.section id="how-it-works" initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} transition={{ staggerChildren: 0.12 }} className="mx-auto max-w-6xl px-6 py-20 lg:px-8"><motion.div variants={reveal} transition={{ duration: 0.45 }} className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-primary">How it works</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">A calmer way to read what you receive.</h2></motion.div><div className="relative mt-12 grid gap-5 md:grid-cols-3"><div className="absolute left-[18%] right-[18%] top-10 hidden h-px bg-gradient-to-r from-primary/20 via-healthcare-pink/30 to-primary/20 md:block" />{steps.map((step, index) => <motion.div key={step.title} variants={reveal} transition={{ duration: 0.45 }}><Card className="relative h-full bg-white/90 text-center"><span className="mx-auto flex size-12 items-center justify-center rounded-2xl gradient-healthcare text-white"><step.icon className="size-5" /></span><p className="mt-5 text-xs font-bold uppercase tracking-widest text-primary">Step {index + 1}</p><CardTitle className="mt-2">{step.title}</CardTitle><CardDescription className="mt-2">{step.description}</CardDescription></Card></motion.div>)}</div></motion.section>
      <motion.section id="features" initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} transition={{ staggerChildren: 0.1 }} className="gradient-healthcare-soft py-20"><div className="mx-auto max-w-6xl px-6 lg:px-8"><motion.div variants={reveal} transition={{ duration: 0.45 }} className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-primary">Built for everyday reports</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Meet the medical language with more clarity.</h2></motion.div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{features.map((feature) => <motion.div key={feature.title} variants={reveal} transition={{ duration: 0.4 }}><Card className="h-full bg-white/85 transition-transform duration-300 hover:-translate-y-1"><CardHeader><span className="flex size-11 items-center justify-center rounded-xl bg-healthcare-lavender text-primary"><feature.icon className="size-5" /></span></CardHeader><CardContent><CardTitle>{feature.title}</CardTitle><CardDescription className="mt-2">{feature.description}</CardDescription></CardContent></Card></motion.div>)}</div></div></motion.section>
      <footer className="border-t border-healthcare-lilac bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-5 px-6 py-9 text-sm sm:flex-row sm:items-center sm:justify-between lg:px-8"><a className="flex items-center gap-2 font-extrabold text-healthcare-ink" href="#top"><HeartPulse className="size-5 text-primary" />Eleos Medical</a><div className="flex gap-5 font-medium text-healthcare-soft-ink"><a className="hover:text-primary" href="#how-it-works">How it works</a><a className="hover:text-primary" href="#features">Features</a><a className="hover:text-primary" href="#top">Privacy</a></div><p className="text-healthcare-soft-ink">Educational support, not medical advice.</p></div></footer>
    </main>
  );
}
